name: myblog
description: Flutter Web Blog backed by Google Sheets (read on web, edit locally)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_highlight: ^0.7.0
  flutter_markdown_plus: ^1.0.6
  go_router: ^17.0.1
  http: ^1.6.0
  intl: ^0.20.2
  yaml: ^3.1.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: fonts/NotoSansKR-Light.ttf
          weight: 300
        - asset: fonts/NotoSansKR-Regular.ttf
          weight: 400
        - asset: fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: fonts/NotoSansKR-Bold.ttf
          weight: 700
    - family: NanumGothicCoding
      fonts:
        - asset: fonts/NanumGothicCoding-Regular.ttf
    - family: Hack
      fonts:
        - asset: fonts/Hack-Regular.ttf
